name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    # - name: Set up Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '20'

    # - name: Install Salesforce CLI
    #   run: npm install -g sfdx-cli

    # - name: Authenticate with Salesforce
    #   run: sfdx force:auth:sfdxurl:store -f authfile.txt -d -a DevHub

    # - name: Create a scratch org
    #   run: sfdx force:org:create -s -f config/project-scratch-def.json -a scratchOrg -d 1 -v DevHub

    # - name: Push source to scratch org
    #   run: sfdx force:source:push

    # - name: Run tests and retrieve coverage
    #   run: |
    #     test_directory="force-app/main/default/classes/test"
    #     class_names=$(find "$test_directory" -name "*.cls" -exec basename {} \; | sed 's/.cls//')
    #     class_names_csv=$(echo "$class_names" | tr '\n' ',' | sed 's/,$//')
    #     sfdx force:apex:test:run --classnames "$class_names_csv" --resultformat=json --codecoverage --outputdir=test-results --wait=10

    # - name: Check test coverage
    #   run: |
    #     COVERAGE=$(jq '.result.summary.testRunCoverage' )
    #     echo "Total Code Coverage: $COVERAGE"
    #     if [ "$COVERAGE" -lt 75 ]; then
    #       echo "Code coverage is below 75%"
    #       exit 1
    #     fi

    - name: Install PMD
      run: |
        wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.44.0/pmd-bin-6.44.0.zip
        unzip pmd-bin-6.44.0.zip -d pmd

    - name: Run PMD Scan
      run: |
        ./pmd/pmd-bin-6.44.0/bin/run.sh pmd -d force-app/main/default/classes -R rulesets/apex/quickstart.xml -f text -r pmd-report.txt || true
        echo "PMD Analysis Completed"

    - name: Check PMD Report
      run: |
        if [ -s pmd-report.txt ]; then
          echo "PMD found issues in the code"
          cat pmd-report.txt
          exit 1
        else
          echo "No PMD issues found"
        fi  

    # - name: Delete scratch org
    #   if: success()
    #   run: sfdx force:org:delete -o scratchOrg -p